In [2]:
a="hai"
print(a)

hai


In [4]:
pip install numpy


     ---------------------------------------- 15.8/15.8 MB 1.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\ABHINAV\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [8]:
import numpy

In [24]:
# zz=numpy.array([1,2,3,4])
# print(zz)

[1 2 3 4]


In [30]:
# print(type())


[10 11 12 13 14]
None


In [31]:
# hh=numpy.array((0,7,8,9))
# print(hh)

[0 7 8 9]


In [37]:
# jj=numpy.array(10)
# print(jj)

10


In [41]:
# ac=numpy.array([[1,2,3,4],[5,6,7,8]])
# print(ac)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
# bd=numpy.array([[[10,11,12,13]],[[14,15,16,17]]])
# print(bd)

[[[10 11 12 13]]

 [[14 15 16 17]]]


In [49]:
#zero dimension
kk=numpy.array(1)
print(kk)
print(kk.ndim)

1
0


In [45]:
#one dimension
ss=numpy.array([10,11,12])
print(ss)

[10 11 12]


In [48]:
# #two dimension
# tt=numpy.array([[20,21,22,23],[24,25,26,27]])
# print(tt)
# print(tt.ndim)

[[20 21 22 23]
 [24 25 26 27]]
2


In [60]:
#three dimension
# pp=numpy.array([[[30,31,32]],[[34,35,36]]])
# print(pp)

[[[30 31 32]]

 [[34 35 36]]]


In [3]:
import numpy as np

In [58]:
# rr=np.array([1,2,3],ndmin=8)
# print(rr)

[[[[[[[[1 2 3]]]]]]]]


In [67]:
# gg=np.array([1,2,3,4])
# print(gg[2]+gg[3])


7


In [79]:
# zz=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# print(zz)
# print(zz[0,2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3


In [84]:
# cc=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(cc)
# print(cc[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [97]:
# ff=np.array([1,2,3,4,5,6,7,8,9,10])
# print(ff)
# print(ff[1:6])
# print(ff[4:7])
# print(ff[1:9:2])
# print(ff[0:9:2])

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[5 6 7]
[2 4 6 8]
[1 3 5 7 9]


In [121]:
# tt=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# # print(tt[1,1:4])
# # print(tt[0,3:5])
# print(tt[1:2,2:5])

[[ 8  9 10]]


In [128]:
# dd=np.array(["zero","one"])
# print(dd[0:2])


['zero' 'one']


In [138]:
# yy=np.array([1,2,3,4,5],dtype="S")
# print(yy)
# print(yy.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [137]:
rr=np.array(["read"])
print(rr)
print(rr.dtype)

['read']
<U4


In [141]:
AA=np.array([1.3,4.3,2.4],dtype=int)
print(AA)
print(AA.dtype)

[1 4 2]
int32


In [11]:
ww=AA.astype("i")
print(ww)
print(ww.dtype)

NameError: name 'AA' is not defined

In [4]:
# qq=np.array([10,11,12,13])
# print(qq.shape)

(4,)


In [5]:
# ff=np.array([[25,26,27,28],[29,30,31,32]])
# print(ff.shape)

(2, 4)


In [6]:
#shaping
# vv=np.array([[[19,20,21,22]],[[99,98,97,96]]])
# print(vv.shape)

(2, 1, 4)


In [20]:
# #reshaping
# ss=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# print(ss.reshape(1,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [22]:
# kk=np.array([1,2,3,4,5])
# gg=np.array([6,7,8,9,10])
# yy=np.concatenate([kk,gg])
# print(yy)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
# zz=np.array([[1,2,3,4],[5,6,7,8]])
# yy=np.array([[10,11,12,13],[14,15,16,17]])
# hh=np.concatenate([zz,yy],axis=1)
# print(hh)

[[ 1  2  3  4 10 11 12 13]
 [ 5  6  7  8 14 15 16 17]]


In [33]:
# pp=np.array([[[1,2,3,4]],[[5,6,7,8]]])
# nn=np.array([[[10,11,12,13]],[[14,15,16,17]]])
# ff=np.concatenate([pp,nn],axis=2)
# print(ff)

[[[ 1  2  3  4 10 11 12 13]]

 [[ 5  6  7  8 14 15 16 17]]]


In [38]:
# #stack
# tt=np.array([1,2,3,4,5])
# mm=np.array([6,7,8,9,10])
# nn=np.stack([tt,mm])
# print(nn)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
# # tt=np.array([1,2,3,4,5])
# mm=np.array([6,7,8,9,10])
# nn=np.hstack([tt,mm])
# print(nn)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
# tt=np.array([1,2,3,4,5])
# mm=np.array([6,7,8,9,10])
# nn=np.dstack([tt,mm])
# print(nn)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [43]:
# tt=np.array([1,2,3,4,5])
# mm=np.array([6,7,8,9,10])
# nn=np.vstack([tt,mm])
# print(nn)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
#split
# tt=np.array([1,2,3,4,5])
# hh=np.array_split(tt,3)
# print(hh)

[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# hh=np.array([1,2,3,4])
# kk=np.array((5,6,7,8))

In [52]:
#zeros concept
# qq=np.zeros(10)
# print(qq)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
# hh=np.zeros((3,2))
# print(hh)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [62]:
# kk=np.zeros((2,3,4))
# print(kk)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [63]:
#ones concept
# bb=np.ones(3)
# print(bb)

[1. 1. 1.]


In [65]:
# hh=np.ones((2,3))
# print(hh)

[[1. 1. 1.]
 [1. 1. 1.]]


In [66]:
# kk=np.ones((1,2,3))
# print(kk)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [68]:
#arange function
# mm=np.arange(1,11)
# print(mm)

[ 1  2  3  4  5  6  7  8  9 10]


In [72]:
# ss=np.arange(10,51,5)
# print(ss)

[10 15 20 25 30 35 40 45 50]


In [74]:
# yy=np.full(10,15)
# print(yy)

[15 15 15 15 15 15 15 15 15 15]


In [90]:
# jj=np.full((2,2),12)
# print(jj)

[[12 12]
 [12 12]]


In [91]:
# vv=np.full((3,3),12)
# print(vv)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [95]:
#random.randint
# dd=np.random.randint(0,10,5)
# print(dd)


[4 0 9 0 8]


In [94]:
# pp=np.random.randint(1,20,6)
# print(pp)

[ 6 14  9  2  3 12]


In [96]:
# aa=np.random.randint(5,10,3)
# print(aa)

[6 8 8]


In [121]:
# tt=np.random.randint(20,40,(2,3))
# print(tt)

[[28 37 29]
 [38 29 38]]


In [124]:
#random.random
# hh=np.random.random(4)
# print(hh)

[0.96422403 0.80315107 0.43746497 0.57742681]


In [127]:
# mm=np.random.random((4,6))
# print(mm)

[[0.93489192 0.35594014 0.08080313 0.54642331 0.87706499 0.58856079]
 [0.88863235 0.30816661 0.2050008  0.79301106 0.01151624 0.91267106]
 [0.75445663 0.612995   0.92293821 0.41341568 0.35934761 0.46920203]
 [0.12320327 0.73919039 0.05020934 0.29042919 0.62251234 0.83521816]]
